# Generated by Django 4.0.6 on 2022-07-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='autos',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='autos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
