# Generated by Django 4.0.6 on 2022-07-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_autos_creation_date_autos_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='stock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
