# Generated by Django 4.0.6 on 2022-08-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0005_servicio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorias',
        ),
    ]
