# Generated by Django 4.0.6 on 2022-08-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0006_categorias_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autos',
            options={'verbose_name': 'Auto', 'verbose_name_plural': 'Autos'},
        ),
        migrations.AddField(
            model_name='autos',
            name='image',
            field=models.ImageField(blank=True, upload_to='cars_image/', verbose_name='Imagen'),
        ),
    ]
