# Generated by Django 4.0.6 on 2022-08-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0006_rename_category_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='image',
            field=models.ImageField(blank=True, upload_to='cars_image/', verbose_name='Imagen'),
        ),
    ]
