# Generated by Django 4.0.6 on 2022-08-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicios',
            name='stock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
