# Generated by Django 4.0.6 on 2022-08-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_servicios_creation_date_servicios_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterField(
            model_name='servicios',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
