# Generated by Django 4.0.6 on 2022-08-21 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=350, verbose_name='Descripción')),
                ('slug', models.SlugField(help_text='url o dirección para ver los detalles del usuario', unique=True, verbose_name='url')),
                ('image', models.ImageField(blank=True, upload_to='profile_image/', verbose_name='Imagen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
