# Generated by Django 4.0.6 on 2022-08-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
