# Generated by Django 4.0.6 on 2022-08-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre Completo'),
        ),
    ]
