# Generated by Django 4.0.6 on 2022-08-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_profile_slug_alter_user_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
