# Generated by Django 4.0.6 on 2022-08-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_last_name_alter_user_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='description',
            field=models.CharField(blank=True, max_length=350, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre'),
        ),
    ]
